### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by xiaojue** [easy-mock/easy-mock#12]
## 出现什么问题？

mac os下 node8.4 安装成功后启动报错。
cnpm install 后无报错，全成功。

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xiaojue/Dev/projects/easy-mock/node_modules/_dtrace-provider@0.6.0@dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xiaojue/Dev/projects/easy-mock/node_modules/_bunyan@1.5.1@bunyan/lib/bunyan.js:34:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32) code: 'MODULE_NOT_FOUND' }
```

## 如何能重现这个问题？

node@8.4.0
cnpm@5.1.1
macos 10.12.5 

## 期望的结果？

不报错，能启动啊…

**Comment by chuangker** [comment]
建议将 Node 先降级到 v7.4.0。

**Comment by xiaojue** [comment]
。。。。。可以 这个方法好。

**Comment by hbrls** [comment]
我手动降级之后仍然需要手动 `$ npm install mv@2.1.1` 才解决了这个问题
