### ISSUE TITLE
开发环境启动项目webpack打包出错

### ISSUE THREAD

**Issue by Luncher** [easy-mock/easy-mock#131]
## OS / Browser Version

 ```javascript

➜  arriw uname -a
Darwin chenlMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

```

浏览器: ` 62.0.3202.94（正式版本） （64 位）`

## Node.js / MongoDB Version

```javascript

➜  arriw node -v
v8.1.2

```

mongo: `3.4.7`

## Steps to reproduce

+ 1. 启动项目

> npm run dev

+ 2. 在app.js新增异常捕获

```javascript

process.on('unhandledRejection', (reason, p) => {
  console.error(reason, 'Unhandled Rejection at Promise', p)
})

```

+ 3. 控制台输出

``` shell

<rejected> ReferenceError: arguments is not defined
    at Object.setHeader (/Users/ytx/work/easy-mock/middlewares/webpack.js:29:28)
    at Object.handleRangeHeaders (/Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/lib/Shared.js:78:8)
    at processRequest (/Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/middleware.js:71:22)
    at Object.ready (/Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/lib/Shared.js:166:29)
    at Object.handleRequest (/Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/lib/Shared.js:209:10)
    at /Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/middleware.js:44:11
    at Promise (<anonymous>)
    at webpackDevMiddleware (/Users/ytx/work/easy-mock/node_modules/webpack-dev-middleware/middleware.js:43:10)
    at Object.<anonymous> (/Users/ytx/work/easy-mock/middlewares/webpack.js:14:5)
    at /Users/ytx/work/easy-mock/node_modules/co/index.js:136:8
    at Promise (<anonymous>)
    at Object.thunkToPromise (/Users/ytx/work/easy-mock/node_modules/co/index.js:135:10)
    at Object.toPromise (/Users/ytx/work/easy-mock/node_modules/co/index.js:119:55)
    at next (/Users/ytx/work/easy-mock/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/ytx/work/easy-mock/node_modules/co/index.js:69:7)
    at /Users/ytx/work/easy-mock/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/ytx/work/easy-mock/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/ytx/work/easy-mock/node_modules/co/index.js:118:63)
    at next (/Users/ytx/work/easy-mock/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/ytx/work/easy-mock/node_modules/co/index.js:69:7)
    at <anonymous> }

```

## What is Expected？

项目正常编译

## What is actually happening？

异常

**Comment by Luncher** [comment]
首次启动的时候还有一个错误：

```shell

{ Error: timeout of 25000ms exceeded
    at createError (/Users/ytx/work/easy-mock/node_modules/axios/lib/core/createError.
js:15:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/Users/ytx/work/easy-mock/node_mo
dules/axios/lib/adapters/http.js:201:16)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 25000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        Authorization: 'Bearer undefined',
        'User-Agent': 'axios/0.15.3',
        host: '127.0.0.1:7300' },
     baseURL: 'http://127.0.0.1:7300/api',
     method: 'get',
     url: 'http://127.0.0.1:7300/api/wallpaper',
     data: undefined },
  code: 'ECONNABORTED',
  response: undefined } 'Unhandled Rejection at Promise' Promise {
  <rejected> { Error: timeout of 25000ms exceeded
    at createError (/Users/ytx/work/easy-mock/node_modules/axios/lib/core/createError.
js:15:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/Users/ytx/work/easy-mock/node_mo
dules/axios/lib/adapters/http.js:201:16)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: [Object],
     transformResponse: [Object],
     timeout: 25000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: [Object],
     baseURL: 'http://127.0.0.1:7300/api',
     method: 'get',
     url: 'http://127.0.0.1:7300/api/wallpaper',
     data: undefined },
  code: 'ECONNABORTED',
  response: undefined } }

```

**Comment by chuangker** [comment]
`http://127.0.0.1:7300/api/wallpaper` 访问正常吗？

**Comment by Luncher** [comment]
![1513746456817](https://user-images.githubusercontent.com/5138977/34192095-d01084ae-e586-11e7-947f-9ed37f1388bb.jpg)

首页在编译完毕的情况下，需要过一些时间才能打开

**Comment by chuangker** [comment]
超过 `25s` 吗？

**Comment by Luncher** [comment]
是的，通过上面的报错也可以看出来，超过`25s`

**Comment by chuangker** [comment]
建议修改该接口，直接返回 `catch` 的内容以避免请求超时。

**Comment by Luncher** [comment]
改了：

```javascript


  this.body = {
    type: 'bing',
    data: [{
      url: '/az/hprichbg/rb/SWFC_ZH-CN9558503653_1920x1080.jpg',
      copyrightlink: '/search?q=%e4%b8%8a%e6%b5%b7%e4%b8%96%e7%95%8c%e9%87%91%e8%9e%8d%e4%b8%ad%e5%bf%83&form=hpcapt&mkt=zh-cn'
    }]
  }

  // try {
  //   const res = yield axios.get(wallpaperAPI)
  //   this.body = unsplashClientId
  //     ? { type: 'unsplash', data: res.data }
  //     : { type: 'bing', data: res.data.images }
  // } catch (error) {

  // }
  unsplashCache.set('one', this.body)

```

**Comment by chuangker** [comment]
改了之后，现在启动还有问题吗？

**Comment by Luncher** [comment]
还有一个问题：

```javascript

    at <anonymous> 'Unhandled Rejection at Promise' Promise {
  <rejected> ReferenceError: arguments is not defined
    at Object.setHeader (/Users/ytx/work/easy-mock/middlewares/webpack.js:29:28)

```

```javascript

  const fun = function * (next) {
    const ctx = this
    ctx.webpack = doIt
    const req = this.req
    const runNext = yield middleware(doIt, req, {
      end: (content) => {
        ctx.body = content
      },
      setHeader: () => {
        ctx.set.apply(ctx, arguments)
      }
    })
    if (runNext) {
      yield * next
    }
  }

```

`setHeader`提示arguments未定义。

**Comment by chuangker** [comment]
怀疑是版本的问题，尝试用 `yarn` 安装一下。

**Comment by Luncher** [comment]
就是用yarn装的

**Comment by Luncher** [comment]
```shell

➜  ~ yarn version
yarn version v0.27.5

```

**Comment by Luncher** [comment]
还没搞清楚为什么，好像跟`babel`或者`node`环境有关系，现在暂时把这个函数改了一下：

```javascript

      setHeader: (...args) => {
        ctx.set.apply(ctx, args)
      }

```

**Comment by chuangker** [comment]
那现在能启动了么？

**Comment by Luncher** [comment]
可以了：），谢谢
