### ISSUE TITLE
npm run dev Failed : SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by jiadexin** [easy-mock/easy-mock#140]
[root@master1 easy-mock]# npm run dev

> easy-mock@1.5.1 dev /opt/gits/easy-mock
> nodemon --ignore views/ --ignore public/ app

[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
/opt/gits/easy-mock/node_modules/koa-jwt/lib/index.js:17
    const middleware = async function jwt(ctx, next) {
                                                    ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gits/easy-mock/app.js:6:16)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ourstorys** [comment]
I met the same problem, how to deal it

**Comment by jiadexin** [comment]
the problem has not been solved yet with me

**Comment by rsl140** [comment]
Node.js (>= v8.9)

**Comment by small-tou** [comment]
Node.js版本的问题
