### ISSUE TITLE
自己部署，多个地方报错 500，请求帮助，谢谢！

### ISSUE THREAD

**Issue by gauseen** [easy-mock/easy-mock#189]
1. 创建接口时报错，但是返回接口列表，还能看到创建的接口！
2. 接口预览也报错！
3. 编辑更新接口时也报错！
```js
Error
Internal Server Error
```
服务器环境：
```sh
node -v
v8.11.1

redis-server --version
Redis server v=4.0.9

 mongo -version
MongoDB shell version v3.6.5
```
具体报错 log
```sh
{"level":50,"time":1529910792460,"msg":"request errored","pid":31230,"hostname":"ip-10-211-18-79","name":"Easy Mock","req":{"id":"af411d79-2e99-4c80-81cd-b40240543b4e","method":"GET","url":"/mock/5b308774e2c97457dab94fe1/api/wx/login","headers":{"host":"10.211.18.79:7300","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://10.211.18.79:7300/project/5b308774e2c97457dab94fe1","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","cookie":"jenkins-timestamper-offset=-28800000; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=YWRtaW46MTUzMDYwMjQzNDQ4Mjo5NGU1NTZlZTllOWRhZTljNTlkMzNjY2Q4ZDc3OWViMTU2YjNhOWQ4NjU4NTkyNWMzYzk3ZDFhZDZmNTNkOThl; easy-mock_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzA4NGExZTJjOTc0NTdkYWI5NGZkOCIsImlhdCI6MTUyOTkxMDc3OCwiZXhwIjoxNTMxMTIwMzc4fQ.WhoTvik3UKbF_d2qEBEVp5z4V24Tp5GtQTeXM-EG0A8"},"remoteAddress":"10.211.63.49","remotePort":61746},"res":{"statusCode":404,"header":null},"err":{"type":"Object","message":"Ready check failed: NOAUTH Authentication required.","stack":"Error: Ready check failed: NOAUTH Authentication required.\n    at /data/www/webproject/easy-mock/node_modules/ioredis/lib/redis/event_handler.js:45:29\n    at /data/www/webproject/easy-mock/node_modules/ioredis/lib/redis.js:412:14\n    at tryCatcher (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise.errorAdapter [as _rejectionHandler0] (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/nodeify.js:35:34)\n    at Promise._settlePromise (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/promise.js:566:21)\n    at Promise._settlePromise0 (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/data/www/webproject/easy-mock/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)"},"v":1}
```

**Comment by chuangker** [comment]
不是都很明显了么？

`Error: Ready check failed: NOAUTH Authentication required`

**Comment by gauseen** [comment]
原来是公司 redis 有密码，小白请教，谢谢大神，解决了
