### ISSUE TITLE
run dev error

### ISSUE THREAD

**Issue by Aquaplast** [easy-mock/easy-mock#208]
## OS / Browser Version
Windows, Latest Google Chrome

## Node.js / MongoDB Version
8.4.0 / 4.0

## Steps to reproduce
npm run dev

## What is actually happening？

```
TypeError: Cannot read property 'data' of undefined
      at server-bundle.js:5331:16
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
{"level":30,"time":1533718579621,"msg":"request completed","pid":6164,"hostname":"whoops","name":"Easy Mock","req":{"id":"920ff1e9-f38a-4f30-a03e-badb1c8bdc13","method":"GET","url":"/","headers":{"host":"localhost:7300","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"127.0.0.1","remotePort":49192},"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nX-Request-Id: 920ff1e9-f38a-4f30-a03e-badb1c8bdc13\r\nVary: Origin\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: 785\r\nDate: Wed, 08 Aug 2018 08:56:19 GMT\r\nConnection: keep-alive\r\n\r\n"},"responseTime":15,"v":1}
(node:6164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: connect EADDRNOTAVAIL 0.0.0.0:7300
```

**Comment by chuangker** [comment]
#195

**Comment by Aquaplast** [comment]
i saw that issue #195, doesn't help
i am already using another solution, so i'll just close this issue

**Comment by Aquaplast** [comment]
123

**Comment by siberiawolf** [comment]
> i saw that issue #195, doesn't help
> i am already using another solution, so i'll just close this issue

Can you talk about how did you fix this issue? I have some trouble with it,too.

And I tried issue #195 solution, didn't work. 

Thanks a lot.
