### ISSUE TITLE
RangeError: Maximum call stack size exceeded at mergeData.

### ISSUE THREAD

**Issue by ThinkRealize** [easy-mock/easy-mock#219]
## OS / Browser Version
MacOS / Chrome 68.0.3440.106
## Node.js / MongoDB Version
v8.11.1 / MongoDB 4.0
## Steps to reproduce
1. npm run dev.
2. Change any vue file .
3. Refresh current page.
## What is Expected？
Show normal page.
## What is actually happening？
Show error.

Error
Looks like something broke!

RangeError: Maximum call stack size exceeded
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1126:20)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/Users/hly/Documents/work/platform/node_modules/vue/dist/vue.runtime.common.js:1137:7)

**Comment by chuangker** [comment]
检查一下 `dependencies` 版本是否一致（重点看下 vue 版本）。

**Comment by ThinkRealize** [comment]
@chuangker 麻烦你了。我检查了 vue-template-compiler、vue、vue-server-renderer 的版本都是一致的  2.5.17。是还有其他包的版本需要检查？问题的描述再说的清晰写，启动后第一次打开页面是正常的，但是修改任何 vue 文件，然后刷新后就会出错。

**Comment by chuangker** [comment]
你应该是理解错了，是让你检查一下 `dependencies`  中指定的版本是否与你本地安装的版本一致。

> 不过，你也可以试试将 vue 降到 2.5.13

**Comment by ThinkRealize** [comment]
2.5.13 测试过，出现一样的问题。同事的 windows 平台也是一样的问题。

**Comment by yibai567** [comment]
遇到一样的问题
正常启动后，页面打开一会报错
Error
Looks like something broke!

        
RangeError: Maximum call stack size exceeded
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1126:20)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)
    at mergeData (/alidata/www/easy-mock/node_modules/vue/dist/vue.runtime.common.js:1137:7)

**Comment by Jesonhu** [comment]
@ThinkRealize  @WenHou 解决了吗，遇到了同样的问题

**Comment by Xuralyon** [comment]
我也遇到了这个问题，node:8.12.0
解决方案：删除pagkage-lock.json，将package.json中锁定所有依赖版本，就是删掉所有的^，然后yarn cache clean，yarn install。目前还没测是哪个依赖出了问题。
