### ISSUE TITLE
npm run start 后不断报NOAUTH Authentication required

### ISSUE THREAD

**Issue by keji94** [easy-mock/easy-mock#241]
错误信息：
`
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at JavascriptRedisParser.returnError (/Users/keji/develop/project/easy-mock/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/Users/keji/develop/project/easy-mock/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/Users/keji/develop/project/easy-mock/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
`

配置文件就用的官方文档上的，环境均已安装。页面是可以访问的，但是设置swagger无效，刷新swagger配置也报这个错误

**Comment by keji94** [comment]
mac环境

**Comment by keji94** [comment]
解决了，redis密码没有设置
