### ISSUE TITLE
部署失败问题反馈

### ISSUE THREAD

**Issue by chuangker** [easy-mock/easy-mock#269]
- **如遇部署失败，请安装 `Node 8.x` 的版本。**
- **如有需要，也可以使用我们提供的 [Docker](https://github.com/easy-mock/easy-mock-docker) 版本。**

**Comment by zhongab** [comment]
请求频率太快，已被限制访问 是什么意思？

**Comment by chuangker** [comment]
> 请求频率太快，已被限制访问 是什么意思？

本地部署的？

**Comment by zhongab** [comment]
> > 请求频率太快，已被限制访问 是什么意思？
> 
> 本地部署的？

是的，现在编译成功
![image](https://user-images.githubusercontent.com/7332300/51308228-9fc0f280-1a7c-11e9-92f1-52e05abb9b10.png)
![image](https://user-images.githubusercontent.com/7332300/51308263-aea7a500-1a7c-11e9-834c-a81f2f3b0dd8.png)

**Comment by zhongab** [comment]
> > > 请求频率太快，已被限制访问 是什么意思？
> > 
> > 
> > 本地部署的？
> 
> 是的，现在编译成功
> ![image](https://user-images.githubusercontent.com/7332300/51308228-9fc0f280-1a7c-11e9-92f1-52e05abb9b10.png)
> ![image](https://user-images.githubusercontent.com/7332300/51308263-aea7a500-1a7c-11e9-834c-a81f2f3b0dd8.png)

是不是配置文件错了，还是哪里问题？能帮忙解决一下？

**Comment by chuangker** [comment]
https://github.com/easy-mock/easy-mock/blob/f02b5fd7e0d3f546b38d559e2ed5b4fc15470239/config/default.json#L15-L18

不要配置黑名单。

**Comment by zhongab** [comment]
> [easy-mock/config/default.json](https://github.com/easy-mock/easy-mock/blob/f02b5fd7e0d3f546b38d559e2ed5b4fc15470239/config/default.json#L15-L18)
> 
> Lines 15 to 18 in [f02b5fd](/easy-mock/easy-mock/commit/f02b5fd7e0d3f546b38d559e2ed5b4fc15470239)
> 
>  "blackList": { 
>    "projects": [], 
>    "ips": [] 
>  }, 
> 不要配置黑名单。

谢谢已经好了，我想问一下这个项目哪里可以查看别人向我发送的请求信息

**Comment by hcznice** [comment]
npm run build 报134错误怎么解决啊，谢谢

**Comment by hcznice** [comment]
本地部署在centon7上面

**Comment by plqin-xiaohao** [comment]
报错 : `WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it. ` 

![image](https://user-images.githubusercontent.com/41833007/54588169-326e1580-4a5d-11e9-9d42-1b85b2ef2500.png)

**Comment by plqin-xiaohao** [comment]
### \#  报错  

```shell
server started at http://0.0.0.0:7300
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
connect to mongodb://localhost/easy-mock error:  failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
```

![image](https://user-images.githubusercontent.com/41833007/54588561-554cf980-4a5e-11e9-9c3c-52b110e33a3a.png)


### \# 环境 : 

```
npm -v
6.4.1

node -v
v10.14.2

Win10 系统
```

**Comment by chuangker** [comment]
> ### # 报错
> ```shell
> server started at http://0.0.0.0:7300
> [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
> connect to mongodb://localhost/easy-mock error:  failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
> ```
> 
> ![image](https://user-images.githubusercontent.com/41833007/54588561-554cf980-4a5e-11e9-9c3c-52b110e33a3a.png)
> 
> ### # 环境 :
> ```
> npm -v
> 6.4.1
> 
> node -v
> v10.14.2
> 
> Win10 系统
> ```

没有启动 `redis`。另外，建议使用 Node `8.x`。

**Comment by plqin-xiaohao** [comment]
@chuangker OK

**Comment by zlyyyy** [comment]
Ubuntu下部署，npm run dev 报错
``` linux
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! easy-mock@1.6.0 build:client: `webpack --config build/webpack.client.config.js --progress --hide-modules`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T03_41_00_222Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! easy-mock@1.6.0 build:dev: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T03_41_00_354Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! easy-mock@1.6.0 build: `cross-env NODE_ENV=production npm run build:dev`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T03_41_00_443Z-debug.log
```
# 环境：
``` linux
npm -v
6.7.0

node -v
v8.11.1

```
已解决，疑似服务器内存不足

**Comment by bq-hentai** [comment]
@hcznice  node 版本切换到 8.x

**Comment by jiaheng6** [comment]
# 报错
![image](https://user-images.githubusercontent.com/20058731/60067124-f2918b00-973b-11e9-91dc-712de475ae70.png)
host用的是`127.0.0.1`，访问用的部署服务器的`w3m http://127.0.0.1:7300`也不行
![image](https://user-images.githubusercontent.com/20058731/60067225-62a01100-973c-11e9-8988-58abdcbc80c7.png)
# 环境
npm 6.9.0
node 8.9.1

**Comment by postblue** [comment]
## 错误提示
![Xnip2019-06-29_03-01-39](https://user-images.githubusercontent.com/39828275/60365008-3e815000-9a1a-11e9-9f7c-8751c6c834df.jpg)
## 运行环境
ubuntu 16.04.1
nvm 0.25.2
node 8.9.1
npm 5.5.1

**Comment by funybaby** [comment]
win7
node  v8.11.4

npm run build 成功
npm run start 成功

项目能正常访问，但是控制台一直打印错误
![image](https://user-images.githubusercontent.com/12585682/64697734-16ab6f80-d4d4-11e9-9a91-09009898c104.png)

**Comment by rockey627** [comment]
> # 报错
> ![image](https://user-images.githubusercontent.com/20058731/60067124-f2918b00-973b-11e9-91dc-712de475ae70.png)
> host用的是`127.0.0.1`，访问用的部署服务器的`w3m http://127.0.0.1:7300`也不行
> ![image](https://user-images.githubusercontent.com/20058731/60067225-62a01100-973c-11e9-8988-58abdcbc80c7.png)
> 
> # 环境
> npm 6.9.0
> node 8.9.1

请问解决了吗？

**Comment by jiaheng6** [comment]
> > # 报错
> > ![image](https://user-images.githubusercontent.com/20058731/60067124-f2918b00-973b-11e9-91dc-712de475ae70.png)
> > host用的是`127.0.0.1`，访问用的部署服务器的`w3m http://127.0.0.1:7300`也不行
> > ![image](https://user-images.githubusercontent.com/20058731/60067225-62a01100-973c-11e9-8988-58abdcbc80c7.png)
> > # 环境
> > npm 6.9.0
> > node 8.9.1
> 
> 请问解决了吗？

没有，好像最后是用Docker装的

**Comment by zhaoxm469** [comment]
{"level":50,"time":1570744645868,"msg":"request errored","pid":27286,"hostname":"VM_0_12_centos","name":"Easy Mock","req":{"id":"2d48497f-8bfd-4665-9141-ea39cb351626","method":"GET","url":"/mock/5d9f1eaa2cbaa746a9486e20/example/mock","headers":{"host":"49.232.22.74:7300","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache","accept":"application/json, */*","user-agent":"Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN","content-type":"application/json","referer":"http://49.232.22.74:7300/mock/5d9f1eaa2cbaa746a9486e20/example/mock","accept-encoding":"gzip, deflate"},"remoteAddress":"42.236.10.93","remotePort":63453},"res":{"statusCode":404,"headers":{"x-request-id":"2d48497f-8bfd-4665-9141-ea39cb351626","vary":"Accept, Origin","rate-limit-remaining":"998","rate-limit-reset":"1570744646","rate-limit-total":"1000"}},"err":{"type":"Error","message":"Topology was destroyed","stack":"MongoError: Topology was destroyed\n    at nextFunction (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:547:27)\n    at Cursor.next [as _next] (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:701:3)\n    at fetchDocs (/home/easy-mock/node_modules/mongodb/lib/cursor.js:857:10)\n    at toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:884:3)\n    at Cursor.toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:837:44)\n    at /home/easy-mock/node_modules/mquery/lib/collection/node.js:30:14\n    at handleCallback (/home/easy-mock/node_modules/mongodb/lib/utils.js:120:56)\n    at Collection.find (/home/easy-mock/node_modules/mongodb/lib/collection.js:384:44)\n    at NativeCollection.<computed> [as find] (/home/easy-mock/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)\n    at NodeCollection.find (/home/easy-mock/node_modules/mquery/lib/collection/node.js:26:19)\n    at model.Query.Query._find (/home/easy-mock/node_modules/mongoose/lib/query.js:1353:27)\n    at /home/easy-mock/node_modules/kareem/index.js:250:8\n    at /home/easy-mock/node_modules/kareem/index.js:23:7\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)"},"v":1}

  MongoError: Topology was destroyed
      at nextFunction (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:547:27)
      at Cursor.next [as _next] (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:701:3)
      at fetchDocs (/home/easy-mock/node_modules/mongodb/lib/cursor.js:857:10)
      at toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:884:3)
      at Cursor.toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:837:44)
      at /home/easy-mock/node_modules/mquery/lib/collection/node.js:30:14
      at handleCallback (/home/easy-mock/node_modules/mongodb/lib/utils.js:120:56)
      at Collection.find (/home/easy-mock/node_modules/mongodb/lib/collection.js:384:44)
      at NativeCollection.<computed> [as find] (/home/easy-mock/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)
      at NodeCollection.find (/home/easy-mock/node_modules/mquery/lib/collection/node.js:26:19)
      at model.Query.Query._find (/home/easy-mock/node_modules/mongoose/lib/query.js:1353:27)
      at /home/easy-mock/node_modules/kareem/index.js:250:8
      at /home/easy-mock/node_modules/kareem/index.js:23:7
      at processTicksAndRejections (internal/process/task_queues.js:75:11)


用着用着 就崩了 不太清楚什么问题导致的

node v12.11.1
mongodb  v4.0.11

**Comment by uu109** [comment]
`npm install` 时报错 `Unexpected end of JSON input while parsing near.................

node v8.9.1
npm v5.5.1`

**Comment by uu109** [comment]
```
Error
Looks like something broke!

        
TypeError: Cannot read property 'data' of undefined
    at server-bundle.js:5403:17
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```


node v8.9.1
npm v5.5.1

**Comment by K-walker** [comment]
@chuangker 我想请教一下，为什么进入docker容器中无法使用sudo命令，我想进入容器修改一些文件

**Comment by K-walker** [comment]
@chuangker 话说我按照你们说的配置，再 production.json 中修改了 fe.publishPath 好像根本没有起作用啊

**Comment by K-walker** [comment]
> @chuangker 我想请教一下，为什么进入docker容器中无法使用sudo命令，我想进入容器修改一些文件

![image](https://user-images.githubusercontent.com/10557092/78418384-32dc4d00-766e-11ea-93f4-cb32e8aa9e39.png)
请问下这个是什么原因

**Comment by K-walker** [comment]
easy-mock@7ef4e4a61475:~/easy-mock$ apt-get install vi
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
easy-mock@7ef4e4a61475:~/easy-mock$

**Comment by K-walker** [comment]
@chuangker 

```shell
easy-mock@7ef4e4a61475:~/easy-mock$ apt-get install vi
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
easy-mock@7ef4e4a61475:~/easy-mock$ 
```
无法安装vi，请问是为何

**Comment by xiaxue008** [comment]
感觉写到这里也没多少人能看得到，新版本的mongo4.x已经不需要像网上那样配置了
被网上的老版本各种教程坑了好久~~

**Comment by soody-1992** [comment]
using node version 8.x works for me.

**Comment by ByXLL** [comment]
npm[13140]: c:\ws\src\node_file.cc:960: Assertion `(argc) == (4)' failed.                                                1: 00007FF68ADB5EBF napi_wrap+114095                                                                                    2: 00007FF68AD60B46 v8::base::CPU::has_sse+66998                                                                        3: 00007FF68AD60EC1 v8::base::CPU::has_sse+67889                                                                        4: 00007FF68AD56F70 v8::base::CPU::has_sse+27104                                                                        5: 00007FF68B52AAE0 v8::internal::Builtins::builtin_handle+323456                                                       6: 00007FF68B52A027 v8::internal::Builtins::builtin_handle+320711                                                       7: 00007FF68B52A368 v8::internal::Builtins::builtin_handle+321544                                                       8: 00007FF68B52A16E v8::internal::Builtins::builtin_handle+321038                                                       9: 00007FF68B9CB4BD v8::internal::SetupIsolateDelegate::SetupHeap+546893                                               10: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                11: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                12: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                13: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                14: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                15: 00007FF68B94969C v8::internal::SetupIsolateDelegate::SetupHeap+14892                                                16: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                17: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                18: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                19: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                20: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                21: 00007FF68B94969C v8::internal::SetupIsolateDelegate::SetupHeap+14892                                                22: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                23: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                24: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                25: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                26: 00007FF68B95036C v8::internal::SetupIsolateDelegate::SetupHeap+42748                                                27: 000001AFED57BF53 

环境：
node v12.18.3
npm v6.14

**Comment by RalapChen** [comment]
Error
Looks like something broke!

        
ReferenceError: document is not defined
    at Object._notification2.default.newInstance (/www/wwwroot/easy-mock/node_modules/iview/dist/iview.js:4727:5)
    at getNoticeInstance (/www/wwwroot/easy-mock/node_modules/iview/dist/iview.js:24816:63)
    at notice (/www/wwwroot/easy-mock/node_modules/iview/dist/iview.js:24838:20)
    at Object.error (/www/wwwroot/easy-mock/node_modules/iview/dist/iview.js:24883:16)
    at module.exports.instance.interceptors.response.use.res (views/api/index.js:74:19)
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
        

完整安装完，服务也成功启动，就是会报500错误

**Comment by luoqiao516** [comment]
node 现在最新版是14  可以支持14吗 谢谢

**Comment by MiakitLuk** [comment]
mongodb 创建的 easy-mock 表不小心给了用户和密码了，如何连接啊， 百度了说是这样子：
mongodb://username:password@localhost:27017/easy-mock?authSource=easy-mock , 弄了半天了，连接 mongo 数据库老是提示错误

**Comment by MiakitLuk** [comment]
![微信截图_20220322180404](https://user-images.githubusercontent.com/49421374/159456312-f76872ac-328c-4c15-b6dc-654bb50fef36.png)
登录提示这个错误，是什么问题呢
