### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by cdoco** [easy-mock/easy-mock#28]
## `[nodemon] app crashed - waiting for file changes before starting...`

```
> easy-mock@1.2.3 dev /data/www/github/easy-mock
> nodemon --debug --ignore views/ app | bunyan -o short

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug app app.js`
(node:29281) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

[nodemon] app crashed - waiting for file changes before starting...
```

### node debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle easy-mock@1.2.3~predev: easy-mock@1.2.3
6 info lifecycle easy-mock@1.2.3~dev: easy-mock@1.2.3
7 verbose lifecycle easy-mock@1.2.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle easy-mock@1.2.3~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/data/www/github/easy-mock/node_modules/.bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/libiconv/bin:/usr/local/sbin:/Users/Cdoco/.cargo/bin:/data/server/php/bin:usr/local/opt/go/libexec/bin:/data/gosrc/src/zygopm:/data/gosrc/bin:/Users/Cdoco/.cargo/bin:/Users/Cdoco/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/libiconv/bin:/usr/local/sbin:/Users/Cdoco/.cargo/bin:/data/server/php/bin:usr/local/opt/go/libexec/bin:/data/gosrc/src/zygopm:/data/gosrc/bin
9 verbose lifecycle easy-mock@1.2.3~dev: CWD: /data/www/github/easy-mock
10 silly lifecycle easy-mock@1.2.3~dev: Args: [ '-c',
10 silly lifecycle   'nodemon --debug --ignore views/ app | bunyan -o short' ]
11 silly lifecycle easy-mock@1.2.3~dev: Returned: code: 1  signal: null
12 info lifecycle easy-mock@1.2.3~dev: Failed to exec dev script
13 verbose stack Error: easy-mock@1.2.3 dev: `nodemon --debug --ignore views/ app | bunyan -o short`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid easy-mock@1.2.3
15 verbose cwd /data/www/github/easy-mock
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error easy-mock@1.2.3 dev: `nodemon --debug --ignore views/ app | bunyan -o short`
22 error Exit status 1
23 error Failed at the easy-mock@1.2.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by chuangker** [comment]
重复的问题，#13
