### ISSUE TITLE
本地部署后访问报错

### ISSUE THREAD

**Issue by bluthly** [easy-mock/easy-mock#280]
/root/.pm2/logs/app-error.log last 15 lines:
0|app      |   TypeError: **Cannot read property 'data' of undefined**
0|app      |       at server-bundle.js:5403:17
0|app      |       at <anonymous>
0|app      |       at process._tickDomainCallback (internal/process/next_tick.js:229:7)
0|app      |
0|app      | Error: Request failed with status code 503
0|app      |     at createError (/application/easymock/easymock/easy-mock/node_modules/axios/lib/core/createError.js:16:15)
0|app      |     at settle (/application/easymock/easymock/easy-mock/node_modules/axios/lib/core/settle.js:18:12)
0|app      |     at IncomingMessage.handleStreamEnd (/application/easymock/easymock/easy-mock/node_modules/axios/lib/adapters/http.js:192:11)
0|app      |     at emitNone (events.js:111:20)
0|app      |     at IncomingMessage.emit (events.js:208:7)
0|app      |     at endReadableNT (_stream_readable.js:1064:12)
0|app      |     at args.(anonymous function) (/application/nodejs/node/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|app      |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
0|app      |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**Comment by codeXian** [comment]
建议看错误日志

**Comment by PBreak** [comment]
同样遇到这个问题，找到解决方法了吗？

**Comment by liuyunxing91** [comment]
你好，我遇到了同样的问题，请问您有解决了吗？

**Comment by liuyunxing91** [comment]
> 同样遇到这个问题，找到解决方法了吗？

请问您有解决吗？我也遇到了同样的问题

**Comment by superman12312** [comment]
`
"port": 7300,  
"host": "localhost",
`  

我修改`host `解决了这个报错。
