### ISSUE TITLE
首次启动出错

### ISSUE THREAD

**Issue by moshuchao** [easy-mock/easy-mock#298]
## OS / Browser Version
maxOS 10.13.6

## Node.js / MongoDB Version
node v8.14.0
MongoDB shell version v3.4.6

## What is actually happening？
```
server started at http://0.0.0.0:7300




  InternalServerError: Internal Server Error
      at Object.throw (/var/koa/easy-mock/node_modules/koa/lib/context.js:92:11)
      at /var/koa/easy-mock/middlewares/view.js:67:20
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by vilian00** [comment]
同遇到，求教解决办法

**Comment by mengdg** [comment]
[nodemon] starting `node app.js`
server started at http://0.0.0.0:7300
(node:16814) ExperimentalWarning: The fs.promises API is experimental
/usr/local/bin/node[16814]: ../src/node_file.cc:829:void node::fs::Stat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) == (3)' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: 0x90dc01 [/usr/local/bin/node]
 3: 0x945599 [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0xb4cf28 [/usr/local/bin/node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x3c57848427d
[nodemon] app crashed - waiting for file changes before starting...

**Comment by funybaby** [comment]
我也遇到同样的问题，有解决的么？
![image](https://user-images.githubusercontent.com/12585682/64698314-3d1dda80-d4d5-11e9-94b0-1d860ddfdeb9.png)
