### ISSUE TITLE
ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378

### ISSUE THREAD

**Issue by succulen-plants** [easy-mock/easy-mock#362]
## OS / Browser Version
mac
## Node.js / MongoDB Version
v11
## What is Expected？
The local deployment reported an error：
npm run dev
```
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6378
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
```

**Comment by ZanderZhang** [comment]
mac node8我这边可以
