### ISSUE TITLE
使用 kubernetes搭建 easy-mock，启动报错

### ISSUE THREAD

**Issue by techqu** [easy-mock/easy-mock#380]
使用 kubernetes 构建 easy-mock，挂载 default.json ，启动后报错

```
/home/easy-mock/easy-mock/node_modules/config/lib/config.js:859
    throw new Error('Config file ' + fullFilename + ' cannot be read');
    ^

Error: Config file /home/easy-mock/easy-mock/config/production.json cannot be read
    at Config.util.parseFile (/home/easy-mock/easy-mock/node_modules/config/lib/config.js:859:11)
    at /home/easy-mock/easy-mock/node_modules/config/lib/config.js:702:28
    at Array.forEach (<anonymous>)
    at /home/easy-mock/easy-mock/node_modules/config/lib/config.js:698:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/home/easy-mock/easy-mock/node_modules/config/lib/config.js:697:13)
    at new Config (/home/easy-mock/easy-mock/node_modules/config/lib/config.js:122:27)
    at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/config/lib/config.js:1767:31)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-mock@1.5.1 start: `cross-env NODE_ENV=production node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-mock@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by techqu** [comment]
已解决
