### ISSUE TITLE
运行一段时间 就挂掉了 

### ISSUE THREAD

**Issue by zhaoxm469** [easy-mock/easy-mock#381]
{"level":50,"time":1570744645868,"msg":"request errored","pid":27286,"hostname":"VM_0_12_centos","name":"Easy Mock","req":{"id":"2d48497f-8bfd-4665-9141-ea39cb351626","method":"GET","url":"/mock/5d9f1eaa2cbaa746a9486e20/example/mock","headers":{"host":"49.232.22.74:7300","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache","accept":"application/json, /","user-agent":"Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN","content-type":"application/json","referer":"http://49.232.22.74:7300/mock/5d9f1eaa2cbaa746a9486e20/example/mock","accept-encoding":"gzip, deflate"},"remoteAddress":"42.236.10.93","remotePort":63453},"res":{"statusCode":404,"headers":{"x-request-id":"2d48497f-8bfd-4665-9141-ea39cb351626","vary":"Accept, Origin","rate-limit-remaining":"998","rate-limit-reset":"1570744646","rate-limit-total":"1000"}},"err":{"type":"Error","message":"Topology was destroyed","stack":"MongoError: Topology was destroyed\n at nextFunction (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:547:27)\n at Cursor.next [as _next] (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:701:3)\n at fetchDocs (/home/easy-mock/node_modules/mongodb/lib/cursor.js:857:10)\n at toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:884:3)\n at Cursor.toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:837:44)\n at /home/easy-mock/node_modules/mquery/lib/collection/node.js:30:14\n at handleCallback (/home/easy-mock/node_modules/mongodb/lib/utils.js:120:56)\n at Collection.find (/home/easy-mock/node_modules/mongodb/lib/collection.js:384:44)\n at NativeCollection. [as find] (/home/easy-mock/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)\n at NodeCollection.find (/home/easy-mock/node_modules/mquery/lib/collection/node.js:26:19)\n at model.Query.Query._find (/home/easy-mock/node_modules/mongoose/lib/query.js:1353:27)\n at /home/easy-mock/node_modules/kareem/index.js:250:8\n at /home/easy-mock/node_modules/kareem/index.js:23:7\n at processTicksAndRejections (internal/process/task_queues.js:75:11)"},"v":1}

MongoError: Topology was destroyed
at nextFunction (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:547:27)
at Cursor.next [as _next] (/home/easy-mock/node_modules/mongodb-core/lib/cursor.js:701:3)
at fetchDocs (/home/easy-mock/node_modules/mongodb/lib/cursor.js:857:10)
at toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:884:3)
at Cursor.toArray (/home/easy-mock/node_modules/mongodb/lib/cursor.js:837:44)
at /home/easy-mock/node_modules/mquery/lib/collection/node.js:30:14
at handleCallback (/home/easy-mock/node_modules/mongodb/lib/utils.js:120:56)
at Collection.find (/home/easy-mock/node_modules/mongodb/lib/collection.js:384:44)
at NativeCollection. [as find] (/home/easy-mock/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)
at NodeCollection.find (/home/easy-mock/node_modules/mquery/lib/collection/node.js:26:19)
at model.Query.Query._find (/home/easy-mock/node_modules/mongoose/lib/query.js:1353:27)
at /home/easy-mock/node_modules/kareem/index.js:250:8
at /home/easy-mock/node_modules/kareem/index.js:23:7
at processTicksAndRejections (internal/process/task_queues.js:75:11)

提示这个错误

**Comment by mapleincode** [comment]
建议查看这个
https://segmentfault.com/a/1190000008565250
