### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by chaixuhong** [easy-mock/easy-mock#396]
modules 116/140 modules 24 active ...odules/js-beautify/js/lib/beautify.jsnode[30057]: ../src/node_file.cc:921:void node::fs::Stat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) == (4)' failed.
 1: 0x95bd00 node::Abort() [node]
 2: 0x95bd87  [node]
 3: 0x967dd2  [node]
 4: 0xbc6d2a  [node]
 5: 0xbc78d9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x19f1a02cfc5d 
sh: line 1: 30045 Aborted                 npm run build:client
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! easy-mock@1.6.0 build:dev: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appadmin/.npm/_logs/2020-03-16T08_59_59_983Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! easy-mock@1.6.0 build: `NODE_ENV=production npm run build:dev`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by chaixuhong** [comment]
等待大神解答，本地win正常，部署到CentOS后 报错

**Comment by liyinchigithub** [comment]
me too

**Comment by JonasGao** [comment]
+1, build with docker, like this

```
FROM node:latest as build-stage
COPY ./easy-mock /easy-mock
WORKDIR /easy-mock
RUN npm ci --registry=https://registry.npm.taobao.org
RUN npm run build:client
```

output
```
> easy-mock@1.6.0 build:client /easy-mock
> webpack --config build/webpack.client.config.js --progress --hide-modules

 25% building modules 127/149 modules 22 active ...easy-mock/views/pages/new/project.vuenode[20]: ../src/node_file.cc:836:void node::fs::Stat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) == (4)' failed.
 1: 0x9e9f40 node::Abort() [node]
 2: 0x9e9fc7  [node]
 3: 0x9f6c72  [node]
 4: 0xbb1b8c  [node]
 5: 0xbb3997 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 6: 0x1391519  [node]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! easy-mock@1.6.0 build:client: `webpack --config build/webpack.client.config.js --progress --hide-modules`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the easy-mock@1.6.0 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T10_07_42_935Z-debug.log
```

2020-3-25 18:30:31 Update

I seen the https://github.com/easy-mock/easy-mock/issues/269. And now using https://github.com/easy-mock/easy-mock-docker

**Comment by JonasGao** [comment]
@chaixuhong Which node version you using? You can try <https://github.com/easy-mock/easy-mock/issues/269>

**Comment by lihua123569** [comment]
me too  centos7.2
13 verbose stack Error: easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid easy-mock@1.6.0
15 verbose cwd /homework/easymock/Easy-Mock
16 verbose Linux 3.10.0-1127.el7.x86_64
17 verbose argv "/homework/node/node/bin/node" "/homework/node/node/bin/npm" "run" "dev"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
22 error Exit status 1
23 error Failed at the easy-mock@1.6.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
