### ISSUE TITLE
centos7.2服务器中启动失败

### ISSUE THREAD

**Issue by lihua123569** [easy-mock/easy-mock#413]
## OS / Browser Version
centos7.2
## Node.js / MongoDB Version
node v12.17.0/ mongodb 4.x
npm  v6.14.4
## Steps to reproduce
npm run dev
## What is Expected？
希望找到问题，解决启动问题
## What is actually happening？
13 verbose stack Error: easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid easy-mock@1.6.0
15 verbose cwd /homework/easymock/Easy-Mock
16 verbose Linux 3.10.0-1127.el7.x86_64
17 verbose argv "/homework/node/node/bin/node" "/homework/node/node/bin/npm" "run" "dev"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
22 error Exit status 1
23 error Failed at the easy-mock@1.6.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by xiaxue008** [comment]
node版本换成8.x试一试呢
