### ISSUE TITLE
The dependency 'chalk' of pm2 have syntax compatibility issues, recommend using Node.js version upper to v8.3.0

### ISSUE THREAD

**Issue by soody-1992** [easy-mock/easy-mock#414]
## OS / Browser Version
CentOS Linux release 8.1.1911 (Core)

## Node.js / MongoDB Version
Node.js v8.0.0
MongoDB mongodb-org v4.2

## Steps to reproduce
1. Install as guide
2. run `NODE_ENV=production pm2 start app.js`

## What is Expected？
easy-mock server start normally.

## What is actually happening？
throw error as follows:
>/home/centos/.nvm/versions/node/v8.0.0/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
	...styles,
	^^^
>
>SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/centos/.nvm/versions/node/v8.0.0/lib/node_modules/pm2/constants.js:10:14)

I try to run `npm run start`, it works normally. So I think it  a spread syntax compatibility issues with Node.js.
On the [MDN Spread Syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) , I found Node.js fully support spread syntax in v8.3.0.
When I replace Node.js v8.0.0 with Node.js v8.3.0,  pm2 can work normally.

Since others may also have this problem, it is recommended to modify the recommended version of Node.js from 8.x to 8.3  in README.

**Comment by soody-1992** [comment]
the pr to fix this problem #415.
