### ISSUE TITLE
Error ! Looks like something broke!

### ISSUE THREAD

**Issue by laoliang330** [easy-mock/easy-mock#418]
npm run dev后服务启动正常，但浏览器访问时报一下错误：
Error
Looks like something broke!

        
InternalServerError: Internal Server Error
    at Object.throw (/root/easy-mock/easy-mock/node_modules/koa/lib/context.js:92:11)
    at /root/easy-mock/easy-mock/middlewares/view.js:67:20
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

node 版本v8.9.1
redis和MongoDB版本和示例一样

**Comment by StayingHungry** [comment]
> npm run dev后服务启动正常，但浏览器访问时报一下错误：
> Error
> Looks like something broke!
> 
> InternalServerError: Internal Server Error
> at Object.throw (/root/easy-mock/easy-mock/node_modules/koa/lib/context.js:92:11)
> at /root/easy-mock/easy-mock/middlewares/view.js:67:20
> at
> at process._tickDomainCallback (internal/process/next_tick.js:228:7)
> 
> node 版本v8.9.1
> redis和MongoDB版本和示例一样

请问解决了吗

**Comment by piscoyu** [comment]
登录页报500是因为动态获取壁纸超时导致，解决办法多刷新几次可以登录了，或者更换网络试下。如果实在不行那改源码喽，将动态获取壁纸的逻辑删掉，自己加个静态壁纸就可以了

**Comment by slowlydd** [comment]
根据楼上大佬的指点，进入源码目录 views/pages/index.vue 文件夹下，注释掉 

asyncData 和 mounted 里边的逻辑（193-206 行）就成功访问了
