### ISSUE TITLE
[Swagger] $ref 引用自身造成死循环

### ISSUE THREAD

**Issue by overstart** [easy-mock/easy-mock#48]
git提交版本 8cb639e - (HEAD) chore: 更新 LICENSE (7 days ago)
报错日志
```json
{"name":"easy-mock","hostname":"liyf-pc","pid":16147,"req_id":"0467dc1a-0b5b-4d0e-b1ec-c6ff659d7b19","level":50,"req":{"method":"POST","url":"/api/project/update_swagger","headers":{"host":"127.0.0.1:7300","connection":"keep-alive","content-length":"33","pragma":"no-cache","cache-control":"no-cache","accept":"application/json, text/plain, */*","origin":"http://127.0.0.1:7300","authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1OWI2NGJhYzNkMTY3ZDI3ZjRhNjJlM2MiLCJleHAiOjE1MDYzMjg3NDksImlkIjoiNTliMWY1ODBkYWEyM2UzNDI2ZWI2NmI3IiwiaWF0IjoxNTA1MTE5MTQ4fQ.g4B54-lJSTf-vlT2AG3qRrZ3cQCoxrAg3zFtv6ubDxs","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://127.0.0.1:7300/project/59b64be33d167d27f4a62e3d","accept-encoding":"gzip, deflate, br","accept-language":"zh-CN,zh;q=0.8","cookie":"token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1OWI2NGJhYzNkMTY3ZDI3ZjRhNjJlM2MiLCJleHAiOjE1MDYzMjg3NDksImlkIjoiNTliMWY1ODBkYWEyM2UzNDI2ZWI2NmI3IiwiaWF0IjoxNTA1MTE5MTQ4fQ.g4B54-lJSTf-vlT2AG3qRrZ3cQCoxrAg3zFtv6ubDxs"},"remoteAddress":"::ffff:127.0.0.1","remotePort":57174},"err":{"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/mdisk/git_repo/easy-mock/node_modules/axios/lib/core/createError.js:15:15)\n    at settle (/mdisk/git_repo/easy-mock/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/mdisk/git_repo/easy-mock/node_modules/axios/lib/adapters/http.js:186:11)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1059:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"},"msg":"  --> POST /api/project/update_swagger, 基于 Swagger 更新 Mock 发生异常","time":"2017-09-12T06:51:25.679Z","v":0}
```
定位代码
```javascript
function _getRefModels (model, swaggerInfo) {
    const type = getType(model)

    // 尝试获取依赖对象, 后面需要增加属性
    let depend = _.get(swaggerInfo, type)

    if (refModels.length === 0) {
      refModels.push(model)
    }

    if (depend) {
      depend = _.cloneDeep(depend)
      depend.properties = depend.properties || {}
      refModels.push(depend.properties)
      Object.keys(depend.properties).forEach((propertie) => {
        propertie = depend.properties[propertie]
        const propertieType = getType(propertie)
        // 防止对象自引用造成栈溢出
        if (propertieType !== type) {
          _getRefModels(propertie, swaggerInfo)
        }
      })
      // 放最后防止循环 _id_，对象别名
      depend.properties._id_ = type.split('.')[1]
    }
  }
```

原因, definition里面模型$ref存在循环嵌套, 这个swagger2.0是允许的

**Comment by angular-moon** [comment]
这个bug近期会得到修复吗?
