### ISSUE TITLE
同学您好！可不可以帮忙看一下 node v8.5.0 mongodb v3.4.6 （npm run dev 启动报500问题）  谢谢！

### ISSUE THREAD

**Issue by iconWave** [easy-mock/easy-mock#67]
### issuses
> node: v8.5.0 
> mongodb：v3.4.9

1、 启动mongodb数据率

2、 启动node开发环境
```
npm run dev
```
3、 浏览器访问 http://127.0.0.1:7300
4、报错误 
```
{
    "name": "easy-mock",
    "hostname": "bogon",
    "pid": 71323,
    "req_id": "d645f268-3ed4-4cb2-8bb8-8ad874192b28",
    "level": 50,
    "req": {
        "method": "GET",
        "url": "/api/project?page_size=30&page_index=1&keywords=&type=&group=&filter_by_author=0",
        "headers": {
            "accept": "application/json, text/plain, */*",
            "authorization": "Bearer undefined",
            "user-agent": "axios/0.15.3",
            "host": "127.0.0.1:7300",
            "connection": "close"
        },
        "remoteAddress": "::ffff:127.0.0.1",
        "remotePort": 58154
    },
    "err": {
        "message": "Invalid secret\n",
        "name": "InternalServerError",
        "stack": "InternalServerError: Invalid secret\n\n    at Object.throw (/Users/bianlifeng/jsResource/easy-mock/node_modules/koa/lib/context.js:89:23)\n    at Object.jwt (/Users/bianlifeng/jsResource/easy-mock/node_modules/koa-jwt/index.js:38:17)\n    at jwt.next (<anonymous>)\n    at Object.<anonymous> (/Users/bianlifeng/jsResource/easy-mock/node_modules/koa-unless/index.js:48:19)\n    at Generator.next (<anonymous>)\n    at onFulfilled (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:65:19)\n    at /Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:54:5\n    at Promise (<anonymous>)\n    at Object.co (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:50:10)\n    at Object.toPromise (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:118:63)\n    at next (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:99:29)\n    at onFulfilled (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:69:7)\n    at /Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:54:5\n    at Promise (<anonymous>)\n    at Object.co (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:50:10)\n    at Object.toPromise (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:118:63)\n    at next (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:99:29)\n    at onFulfilled (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:69:7)\n    at /Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:54:5\n    at Promise (<anonymous>)\n    at Object.co (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:50:10)\n    at Object.toPromise (/Users/bianlifeng/jsResource/easy-mock/node_modules/co/index.js:118:63)"
    },
    "msg": "  --> GET /api/project?page_size=30&page_index=1&keywords=&type=&group=&filter_by_author=0 500",
    "time": "2017-09-16T07:25:27.234Z",
    "v": 0
}{
    "name": "easy-mock",
    "hostname": "bogon",
    "pid": 71323,
    "req_id": "c273f1b9-078f-4226-bb37-7c7cbe12e7dc",
    "level": 50,
    "msg": "error during render : /",
    "time": "2017-09-16T07:25:27.368Z",
    "v": 0
}{
    "name": "easy-mock",
    "hostname": "bogon",
    "pid": 71323,
    "req_id": "c273f1b9-078f-4226-bb37-7c7cbe12e7dc",
    "level": 50,
    "msg": "TypeError: Cannot read property 'data' of undefined\n    at server-bundle.js:1782:16\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
    "time": "2017-09-16T07:25:27.368Z",
    "v": 0
}
```

5、定位错误：可以从这段返回字段中看出是js抛出的错误：   
```
"msg": "TypeError: Cannot read property 'data' of undefined\n    at server-bundle.js:1782:16\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
```

> 希望大佬看到后能帮忙解决下。无尽的感谢！

**Comment by ronesam** [comment]
首次访问主页, 需要加上"/"

**Comment by linesoft** [comment]
我也是，之前版本可以启动，目前最新版本，window环境，启动直接报500错误
`500 | Internal Server Error` 
求修复

**Comment by chuangker** [comment]
估计没有配置 secret 字段。

**Comment by chuangker** [comment]
重复的问题，#69
