### ISSUE TITLE
Swagger API文档导入后没有创建接口？

### ISSUE THREAD

**Issue by kungfuboy** [easy-mock/easy-mock#82]
Swagger的json格式的接口文档是这个，外网可以访问：http://hyhz.ygsoft.com/cooco-mgr/v2/api-docs?group=demo

但导入后没有成功创建出接口。

是否有哪里配置得不对？还是swagger文档有什么问题？谢谢~

![image](https://user-images.githubusercontent.com/10394818/30698391-68037334-9f14-11e7-96f8-19d53ceb1272.png)

**Comment by lcnju** [comment]
看下你的error.log日志，应该是swagger生成api文件的时候有死循环，导致栈爆了，我也遇到了

```
RangeError: Maximum call stack size exceeded
at baseGetTag (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:3074:24)
at baseClone (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2663:19)
at /home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2702:34
at arrayEach (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:537:11)
at baseClone (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2696:7)
at /home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2702:34
at arrayEach (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:537:11)
at baseClone (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2696:7)
at /home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2702:34
at arrayEach (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:537:11)
at baseClone (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:2696:7)
at Function.cloneDeep (/home/easy-mock/easy-mock/node_modules/lodash/lodash.js:11102:14)
at _getRefModels (/home/easy-mock/easy-mock/util/swagger.js:81:18)
at Object.keys.forEach (/home/easy-mock/easy-mock/util/swagger.js:89:11)
at Array.forEach (<anonymous>)
at _getRefModels (/home/easy-mock/easy-mock/util/swagger.js:84:38)
at Object.keys.forEach (/home/easy-mock/easy-mock/util/swagger.js:89:11)
at Array.forEach (<anonymous>)
at _getRefModels (/home/easy-mock/easy-mock/util/swagger.js:84:38)
at Object.keys.forEach (/home/easy-mock/easy-mock/util/swagger.js:89:11)
at Array.forEach (<anonymous>)
at _getRefModels (/home/easy-mock/easy-mock/util/swagger.js:84:38)"
```

**Comment by kungfuboy** [comment]
能不能通过上传swagger.json文档生成API？在哪里有上传功能吗？

**Comment by lcnju** [comment]
目前没有

**Comment by xinyu198736** [comment]
@kungfuboy 这个功能在规划
